apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana-pusher-mysql
  namespace: @@NAMESPACE@@
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem