---
apiVersion: v1
data:
  MARIADB_ROOT_PASSWORD: @@MARIADB_ROOT_PASSWORD@@
  MARIADB_PASSWORD: @@MARIADB_PASSWORD@@=
kind: Secret
metadata:
  name: mysql-secret
  namespace: @@NAMESPACE@@
type: Opaque
---
apiVersion: v1
data:
  MARIADB_DATABASE: grafanapusher
  MARIADB_USER: grafanapusher
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: @@NAMESPACE@@
